services:
  mysql:
    image: mysql:8.0
    container_name: eventhub-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: eventhub
      MYSQL_USER: appuser
      MYSQL_PASSWORD: apppassword
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  app:
    build: .
    container_name: eventhub-app
    restart: always
    depends_on:
      - mysql
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker   # 👈 Forces app to use docker.properties
    volumes:
      - ./logs:/app/logs

volumes:
  mysql_data:
